### ISSUE TITLE
Terraform Provider Development Program - Review

### ISSUE THREAD

**Issue by cgriggs01** [stackpath/terraform-provider-stackpath#8] opened 2019-09-26 23:14 UTC
Hi Team,

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the develop branch at git commit `be530a8`

- [x] The resource file naming convention is as follows, `resource_providername_resource_name.go` which means the file `detector.go` should be named `resource_signalfx_detector.go` and its corresponding acceptance test should be named `resource_signalfx_detector_test.go` , this should be follows across all resource files.  

- [x] All the attributes should be read and set on READ so that differences between the configuration and the actual state can be caught. Any non-scalar values (TypeList, TypeSet, TypeMap) should have errors checked when setting. This is important because the provider should error out and never panic. Take a look at the [GitHub provider](https://github.com/terraform-providers/terraform-provider-github/blob/master/github/resource_github_branch_protection.go#L237) for an example. This practice should be applied for attribute like [ingress](https://github.com/stackpath/terraform-provider-stackpath/blob/master/stackpath/resource_compute_network_policy.go#￼￼L400).

- [x] You will need to build website documentation in a website/ directory that will be hosted on [Terraform.io](Terraform.io/docs/providers/index.html) for each resource and data source, these are all written in Markdown with a ruby layout file for the sidebar formatting.  Check out the [Github provider](https://github.com/terraform-providers/terraform-provider-github) website docs as a good example. 

- [x] The provider.go attributes `client_id`, `client_secret` and `access_token` should be configured to be set with environment variable. Something like STACKPATH_CLIENT_ID would be great.

- [x] The test credentials you had submitted though the [form](https://goo.gl/forms/iqfz6H9UK91X9LQp2) were not in a format that I could decrypt. Could you please resubmit the test credentials so that we can start testing the provider.

**Comment by klaude** [comment] 2019-09-27 16:20
Howdy, @cgriggs01! 

Thanks for the list. We'll hop right on this. How would you like to be updated on our progress? We'll likely take care of these in multiple pull requests. We can tag this issue number in the PR or tag you directly if you'd like to check them out. Whatever is easiest for you and your team works for us. Thanks!

**Comment by klaude** [comment] 2019-09-27 16:39
@cgriggs01, we've resubmitted the test credentials form, this time using local GPG instead of keybase's GPG. If this one doesn't work please hit me up directly at kevin.laude@stackpath.com, and we'll figure it out.

**Comment by klaude** [comment] 2019-10-21 19:26
@cgriggs01, regarding:

> The provider.go attributes `client_id`, `client_secret` and `access_token` should be configured to be set with environment variable. Something like STACKPATH_CLIENT_ID would be great.

The config's [`LoadAndValidate()`](https://github.com/stackpath/terraform-provider-stackpath/blob/master/stackpath/config.go#L62) function uses `os.GetEnv()` to set default values from environment values. Is that alright, or would you rather we use `schema.EnvDefaultFunc()` in the provider definition?

**Comment by klaude** [comment] 2019-10-26 02:54
@cgriggs01, I think we got everything taken care of. How does it look to you? Did the re-submitted credentials work out?

**Comment by cgriggs01** [comment] 2019-10-29 15:29
Thanks for the update. I'll was able to run them but am not having any success. This was from the latest commit `be9edb8`. 

[test.txt](https://github.com/stackpath/terraform-provider-stackpath/files/3784364/test.txt)

What should i be setting `STACKPATH_STACK` to?

**Comment by klaude** [comment] 2019-10-29 17:56
It looks like the 404s you're seeing are due to an invalid stack ID. The `stack` provider field or `STACKPATH_STACK` environment variable should be set to the stack's ID instead of the name. The easiest way to find the ID is to log into our control panel, head to any page that deals with the stack, then look at the page's URL. It should look something like `https://control.stackpath.com/stacks/91ae3521-8ab3-4881-909b-969a4ac0aaae/dashboard`. The stack ID is the part after "stacks/". 

I'll rename the provider field to `stack_id` and environment variable `STACKPATH_STACK_ID`. If you ran into this issue then it's very likely other Terraform users would to. A more descriptive variable name may help make that clearer. 

If you're having any trouble finding the stack ID hit me up directly at kevin.laude@stackpath.com and I can get you the right value to use. Otherwise, how do things look after setting the stack ID?

**Comment by cgriggs01** [comment] 2019-10-29 23:33
Thanks for the help. I've got the `stack_id` now. Still getting a failed test run thought. See attached output. 

[test.txt](https://github.com/stackpath/terraform-provider-stackpath/files/3786223/test.txt)

**Comment by klaude** [comment] 2019-10-30 04:25
The error `oauth2: cannot fetch token: 404 Not Found` implies that the client ID is incorrect. It should be a 32 character hexadecimal string. I'm not sure if we provided you with a client ID and secret or with control panel login information. If it's the latter then generate a client ID and secret at https://control.stackpath.com/api-management . If your client ID and secret look right then please contact me directly so we can figure out what's going on with your account. Thanks!

**Comment by cgriggs01** [comment] 2019-10-31 15:52
Thanks @klaude 

That makes sense now, I got the correct credentials for running the acceptance tests. They are looking better but still failing a few tests. See [test.txt](https://github.com/stackpath/terraform-provider-stackpath/files/3791493/test.txt) for details.

**Comment by klaude** [comment] 2019-10-31 19:06
I see the same error on my test account. I'll poke away at it and let you know what I find. Thanks!

**Comment by klaude** [comment] 2019-10-31 21:42
@cgriggs01, we found the cause of the error, and I snuck a fix for it into #12. I'm running into other errors in the functional test suite, and we'll have fixes for that coming soon too. I'll shout out when we've got this ready to test again. Thanks for your patience.

**Comment by klaude** [comment] 2019-12-03 23:27
Whew, thanks for waiting on us, @cgriggs01. We've merged #12 in, and the functional suite passes for me now. When you're available can you give this a try again?

**Comment by cgriggs01** [comment] 2019-12-04 01:08
Everything looks great @klaude, thanks for all your work on this.

There is just one last item before I can start the migration and release process. The new reopsiotory location will be `github.com/terraform-providers/terraform-provider-stackpath/`, can you update that import path throughout the provider. So anything that is importing `github.com/stackpath/terraform-provider-stackpath/` should be updated.  If it works better for you, this changes can be added to a separate branch if any changes conflict with your current build process.  

Once this is complete we'll begin the migration.

**Comment by klaude** [comment] 2019-12-04 16:52
I've migrated the package over. It's in the `[terraform-import-paths](https://github.com/stackpath/terraform-provider-stackpath/tree/terraform-import-paths)` branch. Let me know what you think. 

Is there anything else you'd like us to do? What are the next steps after this is migrated to github.com/terraform-providers? I assume all changes should go to the new repository while we maintain a fork here for development.

**Comment by cgriggs01** [comment] 2019-12-04 18:17
Great, thanks @klaude 

I'll start the process. It will begin with the creation of the new empty repo and we'll push this code up under the master branch, where the published binary will be pulled from. A Changelog.md will be added, with an initial release version of "1.0.0" a(Semantic versioning)and a additional script [changelog-links.sh](https://github.com/terraform-providers/terraform-provider-github/blob/master/scripts/changelog-links.sh) that's used during the release process. For the terraform.io website documentation, we will create a stable-website branch where the website builder pulls from. 

You and whoever else needs access will be onboarded as maintainers to the Stackpath provider and granted write access over the repo as well a TeamCity account to view nightly acceptance tests and Slack access for request new versioned releases of the provider. Releases are triggered manually by a Terraform ecosystem engineer. Feel free to email [me](chris@hashicorp.com) a list of emails and Github username of maintainers.

You are free to maintainer this repo and continue development, but be aware that since the binary is being built from the new location, user will come there to submit issues and PRs, so you should continue to monitor the new repository.  

Let me know if you have any questions!

**Comment by klaude** [comment] 2019-12-04 21:34
I've emailed you, @cgriggs01. We'll keep watch over the new repo. Is there anything else you'd like us to do?

**Comment by klaude** [comment] 2019-12-17 20:46
Looks like everything it going along well with the [new fandangled official provider](https://github.com/terraform-providers/terraform-provider-stackpath), so I'm going to close this out. Thanks for all your help, @cgriggs01 !

**Closed by klaude** 2019-12-17 20:46 UTC
Labels: enhancement
